Require "active_support" before specific modules
Supposedly it's always been required when not loading Rails:

  https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support

...but I don't think I've had any issues with it before Rails 7

Without this we get errors when running isolated specs:

    NoMethodError:
      undefined method `deprecator' for ActiveSupport:Module

...which prevents us from running `git --bisect` to debug.

Don't bother explicitly including it when
spec/support/time_formats_helper.rb is included, since that includes
"active_support", but put it first before other specific modules are
loaded.