(fix) Only require rubocop in test
The issue here is that rubocop is only loaded in development and test,
but the Rakefile is executed in all environments. This leads to a
failure when trying to deploy to heroku, since gems which are only dev
or test aren't actually available. The resulting error lines include:

```
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: cannot load such file -- rubocop/rake_task
```

```
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/soldn-staging.git'
```